# Generated by Django 5.0.7 on 2024-07-17 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='key',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
